from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from app.models.exercise import DifficultyLevel


def _case(args: Sequence[Any], expected: Any) -> dict[str, Any]:
    return {"args": list(args), "expected": expected}


def _build_prompt(title: str, description: str, signature: str, examples: Sequence[dict[str, Any]]) -> str:
    lines = [
        f"Implement **{title}** as a Python function.",
        "",
        description,
        "",
        f"Function signature: `{signature}`",
        "",
        "Examples:",
    ]
    for example in examples[:2]:
        lines.append(f"- Input: `{example['input']}`")
        lines.append(f"  Output: `{example['output']}`")
    return "\n".join(lines)


def _build_problem(
    *,
    slug: str,
    title: str,
    topic: str,
    subtopic: str,
    difficulty: DifficultyLevel,
    description: str,
    signature: str,
    examples: Sequence[dict[str, Any]],
    tests: Sequence[dict[str, Any]],
    tags: Sequence[str],
) -> dict[str, Any]:
    prompt_markdown = _build_prompt(title, description, signature, examples)
    return {
        "slug": slug,
        "title": title,
        "topic": topic,
        "subtopic": subtopic,
        "difficulty": difficulty,
        "prompt_markdown": prompt_markdown,
        "constraints_json": {
            "runtime": {
                "language": "python",
                "functionName": "solve",
                "signature": signature,
                "starterCode": "def solve(*args):\n    pass\n",
                "tests": list(tests),
            }
        },
        "expected_outcomes_json": [
            "Produces the correct answer for the provided test cases",
            "Handles edge cases without special-casing the examples",
            "Keeps the implementation clean and readable",
        ],
        "hints_json": [
            f"Reduce the problem to the {subtopic} pattern.",
            "Write down the edge cases before coding the main path.",
        ],
        "canonical_solution_json": None,
        "tags": ["leetcode", topic, subtopic, difficulty.value],
    }


LEETCODE_PROBLEMS: Sequence[dict[str, Any]] = (
    _build_problem(
        slug="two-sum",
        title="Two Sum",
        topic="arrays",
        subtopic="hash-map lookup",
        difficulty=DifficultyLevel.easy,
        description="Return the zero-based indices of the two numbers whose sum equals `target`.",
        signature="def solve(nums: list[int], target: int) -> list[int]:",
        examples=(
            {"input": "solve([2, 7, 11, 15], 9)", "output": [0, 1]},
            {"input": "solve([3, 2, 4], 6)", "output": [1, 2]},
        ),
        tests=(
            _case(([2, 7, 11, 15], 9), [0, 1]),
            _case(([3, 2, 4], 6), [1, 2]),
            _case(([3, 3], 6), [0, 1]),
        ),
        tags=("leetcode", "arrays", "hash-map"),
    ),
    _build_problem(
        slug="contains-duplicate",
        title="Contains Duplicate",
        topic="arrays",
        subtopic="sets",
        difficulty=DifficultyLevel.easy,
        description="Return `True` when any value appears at least twice.",
        signature="def solve(nums: list[int]) -> bool:",
        examples=(
            {"input": "solve([1, 2, 3, 1])", "output": True},
            {"input": "solve([1, 2, 3, 4])", "output": False},
        ),
        tests=(
            _case(([1, 2, 3, 1],), True),
            _case(([1, 2, 3, 4],), False),
            _case(([1, 1, 1, 3, 3, 4, 3, 2, 4, 2],), True),
        ),
        tags=("leetcode", "arrays", "sets"),
    ),
    _build_problem(
        slug="valid-anagram",
        title="Valid Anagram",
        topic="strings",
        subtopic="frequency counting",
        difficulty=DifficultyLevel.easy,
        description="Return `True` when `t` is an anagram of `s`.",
        signature="def solve(s: str, t: str) -> bool:",
        examples=(
            {"input": "solve('anagram', 'nagaram')", "output": True},
            {"input": "solve('rat', 'car')", "output": False},
        ),
        tests=(
            _case(("anagram", "nagaram"), True),
            _case(("rat", "car"), False),
            _case(("aacc", "ccac"), False),
        ),
        tags=("leetcode", "strings", "frequency"),
    ),
    _build_problem(
        slug="best-time-to-buy-and-sell-stock",
        title="Best Time to Buy and Sell Stock",
        topic="arrays",
        subtopic="one-pass scan",
        difficulty=DifficultyLevel.easy,
        description="Return the maximum profit from one buy and one sell.",
        signature="def solve(prices: list[int]) -> int:",
        examples=(
            {"input": "solve([7, 1, 5, 3, 6, 4])", "output": 5},
            {"input": "solve([7, 6, 4, 3, 1])", "output": 0},
        ),
        tests=(
            _case(([7, 1, 5, 3, 6, 4],), 5),
            _case(([7, 6, 4, 3, 1],), 0),
            _case(([1, 2],), 1),
        ),
        tags=("leetcode", "arrays", "scan"),
    ),
    _build_problem(
        slug="maximum-subarray",
        title="Maximum Subarray",
        topic="arrays",
        subtopic="dynamic programming",
        difficulty=DifficultyLevel.medium,
        description="Return the largest sum of a contiguous subarray.",
        signature="def solve(nums: list[int]) -> int:",
        examples=(
            {"input": "solve([-2,1,-3,4,-1,2,1,-5,4])", "output": 6},
            {"input": "solve([1])", "output": 1},
        ),
        tests=(
            _case(([-2, 1, -3, 4, -1, 2, 1, -5, 4],), 6),
            _case(([1],), 1),
            _case(([5, 4, -1, 7, 8],), 23),
        ),
        tags=("leetcode", "arrays", "dp"),
    ),
    _build_problem(
        slug="product-of-array-except-self",
        title="Product of Array Except Self",
        topic="arrays",
        subtopic="prefix and suffix",
        difficulty=DifficultyLevel.medium,
        description="Return an array where each position contains the product of all other numbers.",
        signature="def solve(nums: list[int]) -> list[int]:",
        examples=(
            {"input": "solve([1, 2, 3, 4])", "output": [24, 12, 8, 6]},
            {"input": "solve([0, 1])", "output": [1, 0]},
        ),
        tests=(
            _case(([1, 2, 3, 4],), [24, 12, 8, 6]),
            _case(([0, 1],), [1, 0]),
            _case(([2, 3, 4, 5],), [60, 40, 30, 24]),
        ),
        tags=("leetcode", "arrays", "prefix-suffix"),
    ),
    _build_problem(
        slug="maximum-product-subarray",
        title="Maximum Product Subarray",
        topic="arrays",
        subtopic="running extrema",
        difficulty=DifficultyLevel.medium,
        description="Return the largest product of any contiguous subarray.",
        signature="def solve(nums: list[int]) -> int:",
        examples=(
            {"input": "solve([2, 3, -2, 4])", "output": 6},
            {"input": "solve([-2, 0, -1])", "output": 0},
        ),
        tests=(
            _case(([2, 3, -2, 4],), 6),
            _case(([-2, 0, -1],), 0),
            _case(([-2, 3, -4],), 24),
        ),
        tags=("leetcode", "arrays", "extrema"),
    ),
    _build_problem(
        slug="find-minimum-in-rotated-sorted-array",
        title="Find Minimum in Rotated Sorted Array",
        topic="arrays",
        subtopic="binary search",
        difficulty=DifficultyLevel.medium,
        description="Return the smallest value in a rotated sorted array with unique values.",
        signature="def solve(nums: list[int]) -> int:",
        examples=(
            {"input": "solve([3, 4, 5, 1, 2])", "output": 1},
            {"input": "solve([4, 5, 6, 7, 0, 1, 2])", "output": 0},
        ),
        tests=(
            _case(([3, 4, 5, 1, 2],), 1),
            _case(([4, 5, 6, 7, 0, 1, 2],), 0),
            _case(([11, 13, 15, 17],), 11),
        ),
        tags=("leetcode", "arrays", "binary-search"),
    ),
    _build_problem(
        slug="search-in-rotated-sorted-array",
        title="Search in Rotated Sorted Array",
        topic="arrays",
        subtopic="binary search",
        difficulty=DifficultyLevel.medium,
        description="Return the index of `target` in a rotated sorted array, or `-1` when absent.",
        signature="def solve(nums: list[int], target: int) -> int:",
        examples=(
            {"input": "solve([4, 5, 6, 7, 0, 1, 2], 0)", "output": 4},
            {"input": "solve([4, 5, 6, 7, 0, 1, 2], 3)", "output": -1},
        ),
        tests=(
            _case(([4, 5, 6, 7, 0, 1, 2], 0), 4),
            _case(([4, 5, 6, 7, 0, 1, 2], 3), -1),
            _case(([1], 0), -1),
        ),
        tags=("leetcode", "arrays", "binary-search"),
    ),
    _build_problem(
        slug="search-insert-position",
        title="Search Insert Position",
        topic="arrays",
        subtopic="binary search",
        difficulty=DifficultyLevel.easy,
        description="Return the index where `target` should be inserted in sorted order.",
        signature="def solve(nums: list[int], target: int) -> int:",
        examples=(
            {"input": "solve([1, 3, 5, 6], 5)", "output": 2},
            {"input": "solve([1, 3, 5, 6], 2)", "output": 1},
        ),
        tests=(
            _case(([1, 3, 5, 6], 5), 2),
            _case(([1, 3, 5, 6], 2), 1),
            _case(([1, 3, 5, 6], 7), 4),
        ),
        tags=("leetcode", "arrays", "binary-search"),
    ),
    _build_problem(
        slug="binary-search",
        title="Binary Search",
        topic="arrays",
        subtopic="binary search",
        difficulty=DifficultyLevel.easy,
        description="Return the index of `target` in a sorted array, or `-1` when absent.",
        signature="def solve(nums: list[int], target: int) -> int:",
        examples=(
            {"input": "solve([-1, 0, 3, 5, 9, 12], 9)", "output": 4},
            {"input": "solve([-1, 0, 3, 5, 9, 12], 2)", "output": -1},
        ),
        tests=(
            _case(([-1, 0, 3, 5, 9, 12], 9), 4),
            _case(([-1, 0, 3, 5, 9, 12], 2), -1),
            _case(([5], 5), 0),
        ),
        tags=("leetcode", "arrays", "binary-search"),
    ),
    _build_problem(
        slug="first-bad-version",
        title="First Bad Version",
        topic="arrays",
        subtopic="binary search",
        difficulty=DifficultyLevel.easy,
        description="Given a version list and the first bad version, return the first bad version.",
        signature="def solve(versions: list[int], first_bad: int) -> int:",
        examples=(
            {"input": "solve([1, 2, 3, 4, 5], 4)", "output": 4},
            {"input": "solve([1, 2, 3, 4, 5], 1)", "output": 1},
        ),
        tests=(
            _case(([1, 2, 3, 4, 5], 4), 4),
            _case(([1, 2, 3, 4, 5], 1), 1),
            _case(([1, 2, 3, 4, 5], 5), 5),
        ),
        tags=("leetcode", "arrays", "binary-search"),
    ),
    _build_problem(
        slug="find-peak-element",
        title="Find Peak Element",
        topic="arrays",
        subtopic="binary search",
        difficulty=DifficultyLevel.medium,
        description="Return any valid peak index where the value is greater than its neighbors.",
        signature="def solve(nums: list[int]) -> int:",
        examples=(
            {"input": "solve([1, 2, 3, 1])", "output": 2},
            {"input": "solve([1, 2, 1, 3, 5, 6, 4])", "output": 1},
        ),
        tests=(
            _case(([1, 2, 3, 1],), 2),
            _case(([1, 2, 1, 3, 5, 6, 4],), 1),
            _case(([1],), 0),
        ),
        tags=("leetcode", "arrays", "binary-search"),
    ),
    _build_problem(
        slug="climbing-stairs",
        title="Climbing Stairs",
        topic="dp",
        subtopic="fibonacci recurrence",
        difficulty=DifficultyLevel.easy,
        description="Return the number of ways to climb `n` stairs when each move is 1 or 2 steps.",
        signature="def solve(n: int) -> int:",
        examples=(
            {"input": "solve(2)", "output": 2},
            {"input": "solve(3)", "output": 3},
        ),
        tests=(
            _case((2,), 2),
            _case((3,), 3),
            _case((5,), 8),
        ),
        tags=("leetcode", "dp", "fibonacci"),
    ),
    _build_problem(
        slug="house-robber",
        title="House Robber",
        topic="dp",
        subtopic="linear DP",
        difficulty=DifficultyLevel.medium,
        description="Return the maximum amount that can be robbed without taking adjacent houses.",
        signature="def solve(nums: list[int]) -> int:",
        examples=(
            {"input": "solve([1, 2, 3, 1])", "output": 4},
            {"input": "solve([2, 7, 9, 3, 1])", "output": 12},
        ),
        tests=(
            _case(([1, 2, 3, 1],), 4),
            _case(([2, 7, 9, 3, 1],), 12),
            _case(([2, 1, 1, 2],), 4),
        ),
        tags=("leetcode", "dp", "linear"),
    ),
    _build_problem(
        slug="coin-change",
        title="Coin Change",
        topic="dp",
        subtopic="minimum coins",
        difficulty=DifficultyLevel.medium,
        description="Return the fewest coins needed to make `amount`, or `-1` when impossible.",
        signature="def solve(coins: list[int], amount: int) -> int:",
        examples=(
            {"input": "solve([1, 2, 5], 11)", "output": 3},
            {"input": "solve([2], 3)", "output": -1},
        ),
        tests=(
            _case(([1, 2, 5], 11), 3),
            _case(([2], 3), -1),
            _case(([1], 0), 0),
        ),
        tags=("leetcode", "dp", "coins"),
    ),
    _build_problem(
        slug="longest-increasing-subsequence",
        title="Longest Increasing Subsequence",
        topic="dp",
        subtopic="subsequence",
        difficulty=DifficultyLevel.medium,
        description="Return the length of the longest strictly increasing subsequence.",
        signature="def solve(nums: list[int]) -> int:",
        examples=(
            {"input": "solve([10, 9, 2, 5, 3, 7, 101, 18])", "output": 4},
            {"input": "solve([0, 1, 0, 3, 2, 3])", "output": 4},
        ),
        tests=(
            _case(([10, 9, 2, 5, 3, 7, 101, 18],), 4),
            _case(([0, 1, 0, 3, 2, 3],), 4),
            _case(([7, 7, 7, 7, 7],), 1),
        ),
        tags=("leetcode", "dp", "subsequence"),
    ),
    _build_problem(
        slug="longest-common-subsequence",
        title="Longest Common Subsequence",
        topic="dp",
        subtopic="2D DP",
        difficulty=DifficultyLevel.medium,
        description="Return the length of the longest common subsequence between two strings.",
        signature="def solve(text1: str, text2: str) -> int:",
        examples=(
            {"input": "solve('abcde', 'ace')", "output": 3},
            {"input": "solve('abc', 'abc')", "output": 3},
        ),
        tests=(
            _case(("abcde", "ace"), 3),
            _case(("abc", "abc"), 3),
            _case(("abc", "def"), 0),
        ),
        tags=("leetcode", "dp", "strings"),
    ),
    _build_problem(
        slug="edit-distance",
        title="Edit Distance",
        topic="dp",
        subtopic="string DP",
        difficulty=DifficultyLevel.hard,
        description="Return the minimum number of insertions, deletions, and substitutions required to convert one string into another.",
        signature="def solve(word1: str, word2: str) -> int:",
        examples=(
            {"input": "solve('horse', 'ros')", "output": 3},
            {"input": "solve('intention', 'execution')", "output": 5},
        ),
        tests=(
            _case(("horse", "ros"), 3),
            _case(("intention", "execution"), 5),
            _case(("kitten", "sitting"), 3),
        ),
        tags=("leetcode", "dp", "strings"),
    ),
    _build_problem(
        slug="container-with-most-water",
        title="Container With Most Water",
        topic="two-pointers",
        subtopic="area maximization",
        difficulty=DifficultyLevel.medium,
        description="Return the maximum water container area from the given heights.",
        signature="def solve(heights: list[int]) -> int:",
        examples=(
            {"input": "solve([1, 8, 6, 2, 5, 4, 8, 3, 7])", "output": 49},
            {"input": "solve([1, 1])", "output": 1},
        ),
        tests=(
            _case(([1, 8, 6, 2, 5, 4, 8, 3, 7],), 49),
            _case(([1, 1],), 1),
            _case(([4, 3, 2, 1, 4],), 16),
        ),
        tags=("leetcode", "two-pointers", "area"),
    ),
    _build_problem(
        slug="trapping-rain-water",
        title="Trapping Rain Water",
        topic="two-pointers",
        subtopic="water trapping",
        difficulty=DifficultyLevel.hard,
        description="Return the total amount of trapped rain water.",
        signature="def solve(heights: list[int]) -> int:",
        examples=(
            {"input": "solve([0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1])", "output": 6},
            {"input": "solve([4, 2, 0, 3, 2, 5])", "output": 9},
        ),
        tests=(
            _case(([0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1],), 6),
            _case(([4, 2, 0, 3, 2, 5],), 9),
            _case(([1, 2, 3, 4],), 0),
        ),
        tags=("leetcode", "two-pointers", "water"),
    ),
    _build_problem(
        slug="kth-largest-element-in-an-array",
        title="Kth Largest Element in an Array",
        topic="heap",
        subtopic="selection",
        difficulty=DifficultyLevel.medium,
        description="Return the `k`th largest element in the array.",
        signature="def solve(nums: list[int], k: int) -> int:",
        examples=(
            {"input": "solve([3, 2, 1, 5, 6, 4], 2)", "output": 5},
            {"input": "solve([3, 2, 3, 1, 2, 4, 5, 5, 6], 4)", "output": 4},
        ),
        tests=(
            _case(([3, 2, 1, 5, 6, 4], 2), 5),
            _case(([3, 2, 3, 1, 2, 4, 5, 5, 6], 4), 4),
            _case(([1], 1), 1),
        ),
        tags=("leetcode", "heap", "selection"),
    ),
    _build_problem(
        slug="valid-parentheses",
        title="Valid Parentheses",
        topic="stack",
        subtopic="matching pairs",
        difficulty=DifficultyLevel.easy,
        description="Return `True` when the brackets are properly balanced and ordered.",
        signature="def solve(text: str) -> bool:",
        examples=(
            {"input": "solve('()[]{}')", "output": True},
            {"input": "solve('(]')", "output": False},
        ),
        tests=(
            _case(("()[]{}",), True),
            _case(("(]",), False),
            _case(("({[]})",), True),
        ),
        tags=("leetcode", "stack", "parens"),
    ),
    _build_problem(
        slug="daily-temperatures",
        title="Daily Temperatures",
        topic="stack",
        subtopic="monotonic stack",
        difficulty=DifficultyLevel.medium,
        description="Return how many days you must wait until a warmer temperature appears.",
        signature="def solve(temperatures: list[int]) -> list[int]:",
        examples=(
            {"input": "solve([73, 74, 75, 71, 69, 72, 76, 73])", "output": [1, 1, 4, 2, 1, 1, 0, 0]},
            {"input": "solve([30, 40, 50, 60])", "output": [1, 1, 1, 0]},
        ),
        tests=(
            _case(([73, 74, 75, 71, 69, 72, 76, 73],), [1, 1, 4, 2, 1, 1, 0, 0]),
            _case(([30, 40, 50, 60],), [1, 1, 1, 0]),
            _case(([30, 60, 90],), [1, 1, 0]),
        ),
        tags=("leetcode", "stack", "monotonic"),
    ),
    _build_problem(
        slug="decode-string",
        title="Decode String",
        topic="strings",
        subtopic="stack parsing",
        difficulty=DifficultyLevel.medium,
        description="Decode nested repetition patterns like `3[a2[c]]`.",
        signature="def solve(text: str) -> str:",
        examples=(
            {"input": "solve('3[a]2[bc]')", "output": "aaabcbc"},
            {"input": "solve('3[a2[c]]')", "output": "accaccacc"},
        ),
        tests=(
            _case(("3[a]2[bc]",), "aaabcbc"),
            _case(("3[a2[c]]",), "accaccacc"),
            _case(("2[abc]3[cd]ef",), "abcabccdcdcdef"),
        ),
        tags=("leetcode", "strings", "stack"),
    ),
    _build_problem(
        slug="longest-substring-without-repeating-characters",
        title="Longest Substring Without Repeating Characters",
        topic="strings",
        subtopic="sliding window",
        difficulty=DifficultyLevel.medium,
        description="Return the length of the longest substring with all unique characters.",
        signature="def solve(text: str) -> int:",
        examples=(
            {"input": "solve('abcabcbb')", "output": 3},
            {"input": "solve('bbbbb')", "output": 1},
        ),
        tests=(
            _case(("abcabcbb",), 3),
            _case(("bbbbb",), 1),
            _case(("pwwkew",), 3),
        ),
        tags=("leetcode", "strings", "window"),
    ),
    _build_problem(
        slug="longest-palindromic-substring",
        title="Longest Palindromic Substring",
        topic="strings",
        subtopic="expand around center",
        difficulty=DifficultyLevel.medium,
        description="Return the longest palindromic substring in the input text.",
        signature="def solve(text: str) -> str:",
        examples=(
            {"input": "solve('babad')", "output": "bab"},
            {"input": "solve('cbbd')", "output": "bb"},
        ),
        tests=(
            _case(("babad",), "bab"),
            _case(("cbbd",), "bb"),
            _case(("forgeeksskeegfor",), "geeksskeeg"),
        ),
        tags=("leetcode", "strings", "palindrome"),
    ),
    _build_problem(
        slug="word-break",
        title="Word Break",
        topic="strings",
        subtopic="dynamic programming",
        difficulty=DifficultyLevel.medium,
        description="Return `True` when the string can be segmented into dictionary words.",
        signature="def solve(text: str, words: list[str]) -> bool:",
        examples=(
            {"input": "solve('leetcode', ['leet', 'code'])", "output": True},
            {"input": "solve('applepenapple', ['apple', 'pen'])", "output": True},
        ),
        tests=(
            _case(("leetcode", ["leet", "code"]), True),
            _case(("applepenapple", ["apple", "pen"]), True),
            _case(("catsandog", ["cats", "dog", "sand", "and", "cat"]), False),
        ),
        tags=("leetcode", "strings", "dp"),
    ),
    _build_problem(
        slug="number-of-islands",
        title="Number of Islands",
        topic="graphs",
        subtopic="grid traversal",
        difficulty=DifficultyLevel.medium,
        description="Return how many islands appear in a 0/1 grid.",
        signature="def solve(grid: list[list[str]]) -> int:",
        examples=(
            {"input": "solve([['1','1','0'],['0','1','0'],['0','0','1']])", "output": 2},
            {"input": "solve([['1','1'],['1','1']])", "output": 1},
        ),
        tests=(
            _case(([['1', '1', '0'], ['0', '1', '0'], ['0', '0', '1']],), 2),
            _case(([['1', '1'], ['1', '1']],), 1),
            _case(([['0', '0'], ['0', '0']],), 0),
        ),
        tags=("leetcode", "graphs", "grid"),
    ),
    _build_problem(
        slug="course-schedule",
        title="Course Schedule",
        topic="graphs",
        subtopic="topological sort",
        difficulty=DifficultyLevel.medium,
        description="Return `True` when all courses can be completed without cyclic prerequisites.",
        signature="def solve(course_count: int, prerequisites: list[list[int]]) -> bool:",
        examples=(
            {"input": "solve(2, [[1, 0]])", "output": True},
            {"input": "solve(2, [[1, 0], [0, 1]])", "output": False},
        ),
        tests=(
            _case((2, [[1, 0]]), True),
            _case((2, [[1, 0], [0, 1]]), False),
            _case((4, [[1, 0], [2, 1], [3, 2]]), True),
        ),
        tags=("leetcode", "graphs", "topological-sort"),
    ),
    _build_problem(
        slug="network-delay-time",
        title="Network Delay Time",
        topic="graphs",
        subtopic="dijkstra",
        difficulty=DifficultyLevel.medium,
        description="Return how long it takes for all nodes to receive a signal from the source.",
        signature="def solve(times: list[list[int]], n: int, k: int) -> int:",
        examples=(
            {"input": "solve([[2,1,1],[2,3,1],[3,4,1]], 4, 2)", "output": 2},
            {"input": "solve([[1,2,1]], 2, 2)", "output": -1},
        ),
        tests=(
            _case(([[2, 1, 1], [2, 3, 1], [3, 4, 1]], 4, 2), 2),
            _case(([[1, 2, 1]], 2, 2), -1),
            _case(([[1, 2, 1]], 2, 1), 1),
        ),
        tags=("leetcode", "graphs", "shortest-path"),
    ),
    _build_problem(
        slug="shortest-path-in-binary-matrix",
        title="Shortest Path in Binary Matrix",
        topic="graphs",
        subtopic="breadth-first search",
        difficulty=DifficultyLevel.medium,
        description="Return the length of the shortest clear path through an 8-direction grid.",
        signature="def solve(grid: list[list[int]]) -> int:",
        examples=(
            {"input": "solve([[0, 1], [1, 0]])", "output": 2},
            {"input": "solve([[0, 0, 0], [1, 1, 0], [1, 1, 0]])", "output": 4},
        ),
        tests=(
            _case(([[0, 1], [1, 0]],), 2),
            _case(([[0, 0, 0], [1, 1, 0], [1, 1, 0]],), 4),
            _case(([[1, 0], [0, 0]],), -1),
        ),
        tags=("leetcode", "graphs", "bfs"),
    ),
    _build_problem(
        slug="task-scheduler",
        title="Task Scheduler",
        topic="greedy",
        subtopic="cooldown scheduling",
        difficulty=DifficultyLevel.medium,
        description="Return the least number of intervals needed to finish all tasks with cooldown `n`.",
        signature="def solve(tasks: list[str], cooldown: int) -> int:",
        examples=(
            {"input": "solve(['A','A','A','B','B','B'], 2)", "output": 8},
            {"input": "solve(['A','C','A','B','D','B'], 1)", "output": 6},
        ),
        tests=(
            _case((["A", "A", "A", "B", "B", "B"], 2), 8),
            _case((["A", "C", "A", "B", "D", "B"], 1), 6),
            _case((["A", "A", "A", "B", "B", "B"], 0), 6),
        ),
        tags=("leetcode", "greedy", "scheduling"),
    ),
    _build_problem(
        slug="subarray-sum-equals-k",
        title="Subarray Sum Equals K",
        topic="arrays",
        subtopic="prefix sums",
        difficulty=DifficultyLevel.medium,
        description="Return the number of contiguous subarrays whose sum equals `k`.",
        signature="def solve(nums: list[int], k: int) -> int:",
        examples=(
            {"input": "solve([1, 1, 1], 2)", "output": 2},
            {"input": "solve([1, 2, 3], 3)", "output": 2},
        ),
        tests=(
            _case(([1, 1, 1], 2), 2),
            _case(([1, 2, 3], 3), 2),
            _case(([1, -1, 0], 0), 3),
        ),
        tags=("leetcode", "arrays", "prefix-sum"),
    ),
    _build_problem(
        slug="count-bits",
        title="Counting Bits",
        topic="bit-manipulation",
        subtopic="dynamic programming",
        difficulty=DifficultyLevel.easy,
        description="Return the number of set bits for every integer from `0` to `n`.",
        signature="def solve(n: int) -> list[int]:",
        examples=(
            {"input": "solve(2)", "output": [0, 1, 1]},
            {"input": "solve(5)", "output": [0, 1, 1, 2, 1, 2]},
        ),
        tests=(
            _case((2,), [0, 1, 1]),
            _case((5,), [0, 1, 1, 2, 1, 2]),
            _case((0,), [0]),
        ),
        tags=("leetcode", "bit-manipulation", "dp"),
    ),
    _build_problem(
        slug="rotate-array",
        title="Rotate Array",
        topic="arrays",
        subtopic="cyclic shifts",
        difficulty=DifficultyLevel.medium,
        description="Rotate the array to the right by `k` steps and return the rotated array.",
        signature="def solve(nums: list[int], k: int) -> list[int]:",
        examples=(
            {"input": "solve([1, 2, 3, 4, 5, 6, 7], 3)", "output": [5, 6, 7, 1, 2, 3, 4]},
            {"input": "solve([-1, -100, 3, 99], 2)", "output": [3, 99, -1, -100]},
        ),
        tests=(
            _case(([1, 2, 3, 4, 5, 6, 7], 3), [5, 6, 7, 1, 2, 3, 4]),
            _case(([-1, -100, 3, 99], 2), [3, 99, -1, -100]),
            _case(([1, 2], 0), [1, 2]),
        ),
        tags=("leetcode", "arrays", "rotation"),
    ),
    _build_problem(
        slug="move-zeroes",
        title="Move Zeroes",
        topic="arrays",
        subtopic="in-place compaction",
        difficulty=DifficultyLevel.easy,
        description="Move all zeroes to the end while preserving the order of non-zero values.",
        signature="def solve(nums: list[int]) -> list[int]:",
        examples=(
            {"input": "solve([0, 1, 0, 3, 12])", "output": [1, 3, 12, 0, 0]},
            {"input": "solve([0])", "output": [0]},
        ),
        tests=(
            _case(([0, 1, 0, 3, 12],), [1, 3, 12, 0, 0]),
            _case(([0],), [0]),
            _case(([1, 2, 3],), [1, 2, 3]),
        ),
        tags=("leetcode", "arrays", "in-place"),
    ),
    _build_problem(
        slug="single-number",
        title="Single Number",
        topic="bit-manipulation",
        subtopic="xor",
        difficulty=DifficultyLevel.easy,
        description="Every value appears twice except one. Return the unique value.",
        signature="def solve(nums: list[int]) -> int:",
        examples=(
            {"input": "solve([2, 2, 1])", "output": 1},
            {"input": "solve([4, 1, 2, 1, 2])", "output": 4},
        ),
        tests=(
            _case(([2, 2, 1],), 1),
            _case(([4, 1, 2, 1, 2],), 4),
            _case(([1],), 1),
        ),
        tags=("leetcode", "bit-manipulation", "xor"),
    ),
    _build_problem(
        slug="missing-number",
        title="Missing Number",
        topic="arrays",
        subtopic="math",
        difficulty=DifficultyLevel.easy,
        description="Return the missing number in the range `0..n`.",
        signature="def solve(nums: list[int]) -> int:",
        examples=(
            {"input": "solve([3, 0, 1])", "output": 2},
            {"input": "solve([0, 1])", "output": 2},
        ),
        tests=(
            _case(([3, 0, 1],), 2),
            _case(([0, 1],), 2),
            _case(([9, 6, 4, 2, 3, 5, 7, 0, 1],), 8),
        ),
        tags=("leetcode", "arrays", "math"),
    ),
    _build_problem(
        slug="majority-element",
        title="Majority Element",
        topic="arrays",
        subtopic="boyer-moore",
        difficulty=DifficultyLevel.easy,
        description="Return the element that appears more than half the time.",
        signature="def solve(nums: list[int]) -> int:",
        examples=(
            {"input": "solve([3, 2, 3])", "output": 3},
            {"input": "solve([2, 2, 1, 1, 1, 2, 2])", "output": 2},
        ),
        tests=(
            _case(([3, 2, 3],), 3),
            _case(([2, 2, 1, 1, 1, 2, 2],), 2),
            _case(([6, 5, 5],), 5),
        ),
        tags=("leetcode", "arrays", "boyer-moore"),
    ),
    _build_problem(
        slug="longest-consecutive-sequence",
        title="Longest Consecutive Sequence",
        topic="arrays",
        subtopic="hash sets",
        difficulty=DifficultyLevel.medium,
        description="Return the length of the longest run of consecutive integers.",
        signature="def solve(nums: list[int]) -> int:",
        examples=(
            {"input": "solve([100, 4, 200, 1, 3, 2])", "output": 4},
            {"input": "solve([0, 3, 7, 2, 5, 8, 4, 6, 0, 1])", "output": 9},
        ),
        tests=(
            _case(([100, 4, 200, 1, 3, 2],), 4),
            _case(([0, 3, 7, 2, 5, 8, 4, 6, 0, 1],), 9),
            _case(([1, 2, 0, 1],), 3),
        ),
        tags=("leetcode", "arrays", "sets"),
    ),
    _build_problem(
        slug="jump-game",
        title="Jump Game",
        topic="greedy",
        subtopic="reachability",
        difficulty=DifficultyLevel.medium,
        description="Return `True` when the last index is reachable from the first index.",
        signature="def solve(nums: list[int]) -> bool:",
        examples=(
            {"input": "solve([2, 3, 1, 1, 4])", "output": True},
            {"input": "solve([3, 2, 1, 0, 4])", "output": False},
        ),
        tests=(
            _case(([2, 3, 1, 1, 4],), True),
            _case(([3, 2, 1, 0, 4],), False),
            _case(([0],), True),
        ),
        tags=("leetcode", "greedy", "reachability"),
    ),
    _build_problem(
        slug="jump-game-ii",
        title="Jump Game II",
        topic="greedy",
        subtopic="minimum jumps",
        difficulty=DifficultyLevel.medium,
        description="Return the minimum number of jumps needed to reach the last index.",
        signature="def solve(nums: list[int]) -> int:",
        examples=(
            {"input": "solve([2, 3, 1, 1, 4])", "output": 2},
            {"input": "solve([2, 3, 0, 1, 4])", "output": 2},
        ),
        tests=(
            _case(([2, 3, 1, 1, 4],), 2),
            _case(([2, 3, 0, 1, 4],), 2),
            _case(([1, 2],), 1),
        ),
        tags=("leetcode", "greedy", "jumps"),
    ),
    _build_problem(
        slug="merge-sorted-array",
        title="Merge Sorted Array",
        topic="arrays",
        subtopic="two pointers",
        difficulty=DifficultyLevel.easy,
        description="Merge two sorted arrays and return the merged result.",
        signature="def solve(nums1: list[int], nums2: list[int]) -> list[int]:",
        examples=(
            {"input": "solve([1, 2, 3], [2, 5, 6])", "output": [1, 2, 2, 3, 5, 6]},
            {"input": "solve([1], [])", "output": [1]},
        ),
        tests=(
            _case(([1, 2, 3], [2, 5, 6]), [1, 2, 2, 3, 5, 6]),
            _case(([1], []), [1]),
            _case(([], [1]), [1]),
        ),
        tags=("leetcode", "arrays", "merge"),
    ),
    _build_problem(
        slug="reverse-words-in-a-string",
        title="Reverse Words in a String",
        topic="strings",
        subtopic="tokenization",
        difficulty=DifficultyLevel.medium,
        description="Reverse the word order and collapse extra spaces.",
        signature="def solve(text: str) -> str:",
        examples=(
            {"input": "solve('  the sky is blue  ')", "output": "blue is sky the"},
            {"input": "solve('hello world')", "output": "world hello"},
        ),
        tests=(
            _case(("  the sky is blue  ",), "blue is sky the"),
            _case(("hello world",), "world hello"),
            _case(("a good   example",), "example good a"),
        ),
        tags=("leetcode", "strings", "parsing"),
    ),
    _build_problem(
        slug="valid-palindrome",
        title="Valid Palindrome",
        topic="strings",
        subtopic="two pointers",
        difficulty=DifficultyLevel.easy,
        description="Return `True` when the text is a palindrome after removing non-alphanumerics and case.",
        signature="def solve(text: str) -> bool:",
        examples=(
            {"input": "solve('A man, a plan, a canal: Panama')", "output": True},
            {"input": "solve('race a car')", "output": False},
        ),
        tests=(
            _case(("A man, a plan, a canal: Panama",), True),
            _case(("race a car",), False),
            _case((" ",), True),
        ),
        tags=("leetcode", "strings", "two-pointers"),
    ),
    _build_problem(
        slug="fizz-buzz",
        title="Fizz Buzz",
        topic="strings",
        subtopic="modulo rules",
        difficulty=DifficultyLevel.easy,
        description="Return the Fizz Buzz sequence up to `n`.",
        signature="def solve(n: int) -> list[str]:",
        examples=(
            {"input": "solve(3)", "output": ["1", "2", "Fizz"]},
            {"input": "solve(5)", "output": ["1", "2", "Fizz", "4", "Buzz"]},
        ),
        tests=(
            _case((3,), ["1", "2", "Fizz"]),
            _case((5,), ["1", "2", "Fizz", "4", "Buzz"]),
            _case((1,), ["1"]),
        ),
        tags=("leetcode", "strings", "basics"),
    ),
    _build_problem(
        slug="plus-one",
        title="Plus One",
        topic="arrays",
        subtopic="carry handling",
        difficulty=DifficultyLevel.easy,
        description="Add one to the integer represented by the digits array.",
        signature="def solve(digits: list[int]) -> list[int]:",
        examples=(
            {"input": "solve([1, 2, 3])", "output": [1, 2, 4]},
            {"input": "solve([9, 9, 9])", "output": [1, 0, 0, 0]},
        ),
        tests=(
            _case(([1, 2, 3],), [1, 2, 4]),
            _case(([9, 9, 9],), [1, 0, 0, 0]),
            _case(([0],), [1]),
        ),
        tags=("leetcode", "arrays", "carry"),
    ),
    _build_problem(
        slug="intersection-of-two-arrays",
        title="Intersection of Two Arrays",
        topic="arrays",
        subtopic="sets",
        difficulty=DifficultyLevel.easy,
        description="Return the unique common values between the two arrays in ascending order.",
        signature="def solve(nums1: list[int], nums2: list[int]) -> list[int]:",
        examples=(
            {"input": "solve([1, 2, 2, 1], [2, 2])", "output": [2]},
            {"input": "solve([4, 9, 5], [9, 4, 9, 8, 4])", "output": [4, 9]},
        ),
        tests=(
            _case(([1, 2, 2, 1], [2, 2]), [2]),
            _case(([4, 9, 5], [9, 4, 9, 8, 4]), [4, 9]),
            _case(([1, 3, 5], [2, 4, 6]), []),
        ),
        tags=("leetcode", "arrays", "sets"),
    ),
    _build_problem(
        slug="ransom-note",
        title="Ransom Note",
        topic="strings",
        subtopic="frequency counting",
        difficulty=DifficultyLevel.easy,
        description="Return `True` when `ransom` can be built from the characters in `magazine`.",
        signature="def solve(ransom: str, magazine: str) -> bool:",
        examples=(
            {"input": "solve('a', 'b')", "output": False},
            {"input": "solve('aa', 'aab')", "output": True},
        ),
        tests=(
            _case(("a", "b"), False),
            _case(("aa", "aab"), True),
            _case(("abcd", "abc"), False),
        ),
        tags=("leetcode", "strings", "frequency"),
    ),
)
